version: '3'
services:
    app-dim0863-ws:
        build:
            context: .
            dockerfile: ./dim0863-ws.dockerfile
            args:
                JAR_FILE: ./target/webserver-0.0.1-SNAPSHOT.jar
        image: luksrn/dim0863-ws
        container_name: DIM0863-ws
        ports:
            - "8080:8080"
